dist: bionic
language: go
go_import_path: github.com/buger/goreplay
go: 1.12
script: sudo -E bash -c "source /etc/profile && eval '$(gimme 1.12)' && export GOPATH=$HOME/gopath:$GOPATH && go get && GORACE='halt_on_error=1' go test ./... -v -timeout 120s -race" || true

services:
  - docker

before_install:
  - sudo apt-get install libpcap-dev -y

jobs:
  include:
    - stage: Build, Unit-Tests & Fuzz-Tests
      go: 1.12.x
      script:
        - ./fuzzit.sh sanity

    - stage: Fuzzit (Fuzzing)
      if: branch = master AND type IN (push)
      go: 1.12.x
      script:
        - ./fuzzit.sh fuzzing
